// This script runs during the Vercel build process.
// It takes the secret VITE_API_KEY from environment variables
// and bakes it into a file that the client-side code can import.
const fs = require('fs');
const path = require('path');

console.log('--- Running build-env.js script ---');

// Create config directory if it doesn't exist
const configDir = path.join(__dirname, 'config');
if (!fs.existsSync(configDir)){
    fs.mkdirSync(configDir);
}

const apiKey = process.env.VITE_API_KEY;
const envFilePath = path.join(configDir, 'env.ts');

if (!apiKey) {
  console.warn('WARNING: VITE_API_KEY environment variable not found. The AI assistant will be disabled.');
  const envContent = `// This file is auto-generated by the build process.\nexport const GEMINI_API_KEY: string | undefined = undefined;\n`;
  fs.writeFileSync(envFilePath, envContent);
  console.log(`Created ${envFilePath} with an undefined API key.`);
} else {
  console.log(`VITE_API_KEY found. Writing to ${envFilePath}.`);
  // Escape backticks in the key to prevent syntax errors
  const escapedApiKey = apiKey.replace(/`/g, '\\`');
  const envContent = `// This file is auto-generated by the build process.\nexport const GEMINI_API_KEY: string | undefined = \`${escapedApiKey}\`;\n`;
  fs.writeFileSync(envFilePath, envContent);
  console.log(`Successfully wrote API key to ${envFilePath}.`);
}

console.log('--- Finished build-env.js script ---');
